### ISSUE TITLE
10.11 Big Sure

### ISSUE THREAD

**Issue by feedlike** [xinsui01/hackintosh-ASUS-ROG-Z390#2]
Are you planning to upload instructions with the OpenCore loader?

**Comment by xinsui01** [comment]
Hi @feedlike ，I have switched to OpenCore bootloader, you can try it.
Enjoy it.
I will try to upgrade to version 10.11 after the official version of Big Sure is released.

**Comment by feedlike** [comment]
Thank. I'll see. What is SMCLightSensor for? is it for laptops?

**Comment by xinsui01** [comment]
It's one of VirtualSMC plugins, not required to boot, and merely add extra functionality to the system like hardware monitoring

- SMCProcessor.kext
    Used for monitoring CPU temperature, doesn't work on AMD CPU based systems
- SMCSuperIO.kext
    Used for monitoring fan speed, doesn't work on AMD CPU based systems
- SMCLightSensor.kext
   Used for the ambient light sensor on laptops, desktops can ignore
   Do not use if you don't have an ambient light sensor, can cause issues otherwise
- SMCBatteryManager.kext
   Used for measuring battery readouts on laptops, desktops can ignore
   Do not use until battery has been properly patched, can cause issues otherwise

You can get more info from  [here](https://dortania.github.io/OpenCore-Install-Guide/ktext.html#kexts)

**Comment by feedlike** [comment]
Thank you!
